import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import "@carbon/styles/index.scss";
// import "@carbon/styles/css/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-10">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
